# This is simplified version of: https://github.com/sei40kr/tmux-onedark/tree/master

set-option -g mode-style 'bg=#3e4452'

set-option -g status-style "bg=#5c6370"
set-option -g status-left-style "bg=#98c379,fg=#282c34"

set-option -g status-right-style "bg=#3e4452,fg=#abb2bf"

set-window-option -g window-status-format ' #I:#W '
set-window-option -g window-status-style "bg=#3e4452"
set-window-option -g window-status-current-format ' #I:#W '
set-window-option -g window-status-current-style "bg=#98c379,fg=#282c34"
set-window-option -g window-status-separator ''
